### ISSUE TITLE
cd shortcuts (like ..) broken on ZSH

### ISSUE THREAD

**Issue by MerlinDE** [cantino/mcfly#116] opened 2020-12-11 08:50 UTC
Sourcing mcfly's `mcfly.zsh`breaks my zsh shortcuts for changing directories (e.g. `..` instead of `cd ..`). It seems to me that the call to `emulate -L zsh` in `mcfly.zsh` resets the `AUTOCD` option, resulting in those shortcuts being broken.

Removing the `emulate` call solved the issue for me. Not sure about any side effects this might cause.

**Comment by cantino** [comment] 2020-12-11 19:06
I'm honestly not sure. I may have cargo culted that setting from an example zsh script.

**Comment by durin42** [comment] 2021-02-18 16:14
This appears to be a duplicate of #91, though I think this has some useful debugging information.

https://github.com/powerline/powerline/commit/98b7ed2950c0432bc2e2c103637bee5dbce0fffe is probably a relevant patch to another project - I might try and take a look at some point.

**Comment by cantino** [comment] 2021-02-27 23:59
I'm not having any issues in zsh with `emulate -L zsh` entirely removed so I'll just remove it.

**Closed** 2021-03-01 18:33 UTC
